// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"

	firestore2 "cloud.google.com/go/firestore"
	"github.com/planetary-social/go-notification-service/internal/logging"
	"github.com/planetary-social/go-notification-service/service/adapters/firestore"
	"github.com/planetary-social/go-notification-service/service/adapters/pubsub"
	"github.com/planetary-social/go-notification-service/service/app"
	"github.com/planetary-social/go-notification-service/service/config"
	"github.com/planetary-social/go-notification-service/service/ports/http"
	pubsub2 "github.com/planetary-social/go-notification-service/service/ports/pubsub"
)

// Injectors from wire.go:

func BuildService(contextContext context.Context, configConfig config.Config) (Service, func(), error) {
	client, err := firestore.NewClient(contextContext, configConfig)
	if err != nil {
		return Service{}, nil, err
	}
	adaptersFactoryFn := newAdaptersFactoryFn()
	transactionProvider := firestore.NewTransactionProvider(client, adaptersFactoryFn)
	saveRegistrationHandler := app.NewSaveRegistrationHandler(transactionProvider)
	commands := app.Commands{
		SaveRegistration: saveRegistrationHandler,
	}
	getRelaysHandler := app.NewGetRelaysHandler(transactionProvider)
	getPublicKeysHandler := app.NewGetPublicKeysHandler(transactionProvider)
	queries := app.Queries{
		GetRelays:     getRelaysHandler,
		GetPublicKeys: getPublicKeysHandler,
	}
	application := app.Application{
		Commands: commands,
		Queries:  queries,
	}
	server := http.NewServer(configConfig, application)
	receivedEventPubSub := pubsub.NewReceivedEventPubSub()
	logger := newLogrus()
	logrusLoggingSystem := logging.NewLogrusLoggingSystem(logger)
	loggingLogger := newSystemLogger(logrusLoggingSystem)
	downloader := app.NewDownloader(transactionProvider, receivedEventPubSub, loggingLogger)
	processReceivedEventHandler := app.NewProcessReceivedEventHandler(transactionProvider, loggingLogger)
	receivedEventSubscriber := pubsub2.NewReceivedEventSubscriber(receivedEventPubSub, processReceivedEventHandler)
	service := NewService(application, server, downloader, receivedEventSubscriber)
	return service, func() {
	}, nil
}

func buildTransactionFirestoreAdapters(client *firestore2.Client, tx *firestore2.Transaction) (app.Adapters, error) {
	relayRepository := firestore.NewRelayRepository(client, tx)
	registrationRepository := firestore.NewRegistrationRepository(client, tx, relayRepository)
	eventRepository := firestore.NewEventRepository(client, tx, relayRepository)
	adapters := app.Adapters{
		Registrations: registrationRepository,
		Events:        eventRepository,
		Relays:        relayRepository,
	}
	return adapters, nil
}
