// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/planetary-social/go-notification-service/service/config"
	"github.com/planetary-social/go-notification-service/service/ports/http"
)

// Injectors from wire.go:

func BuildService(configConfig config.Config) (Service, func(), error) {
	server := http.NewServer(configConfig)
	service := NewService(server)
	return service, func() {
	}, nil
}
